[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version" # prevent Netlify npm install
[build]
  base = "/"
  publish = "dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store --frozen-lockfile && npx pnpm run build"
